app:
  name: "Web_app"
  mode: "dev"
  port: "127.0.0.1:8081"
  version: "v0.1.3"
  machine_id: 1
  start_time: "2024-03-03"
  auth: 
    jwt_expire:  8760
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_connections: 200
  max_idle_col: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  poolsize: 100


